### ISSUE TITLE
[Documentation] Compiling Instructions

### ISSUE THREAD

**Issue by RussellAult** [WLANThermo-nano/WLANThermo_ESP32_Software#165]
I can't seem to find instructions for compiling the WLANThermo ESP32 software in the source, the Wiki, or the forums. Am I missing them?

Thanks!

**Comment by sochs** [comment]
It's a platformio project, so it's pretty simple: Install [Visual Studio Code](https://code.visualstudio.com/), integrate [platformio](https://platformio.org/install/ide?install=vscode), open the [project code](https://github.com/WLANThermo-nano/WLANThermo_ESP32_Software), select the hardware to be compiled and go. All necessary libs etc. are organized by platformio. 
But it is only necessary to compile if you have changed something in the code. Otherwise, simply upload the finished BIN firmware live from a [release](https://github.com/WLANThermo-nano/WLANThermo_ESP32_Software/releases) using the recovery mode or use the online update function.
